services:
  app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    tty: true
    stdin_open: true
    init: true
    environment:
      TZ: Asia/Tokyo
      CHOKIDAR_USEPOLLING: 1
      HOST: 0.0.0.0
    ports:
      - "13702:13702"
    working_dir: /app/
    volumes:
      - ./:/app/

  db:
    build:
      context: ./
      dockerfile: ./docker/db/Dockerfile
    tty: true
    stdin_open: true
    ports:
      - "13703:8080"
    environment:
      TZ: Asia/Tokyo
      COCKROACH_USER: root
      COCKROACH_PASSWORD: root
    command: start-single-node --insecure
